codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: 10...90
  
ignore:
  - "app/src/main/java/bookcase/App.java"
  - "app/src/main/java/bookcase/dao/DAO.java"
  - "app/src/main/java/bookcase/domain/LibraryObject.java"
  